[package]
name = "multer-derive-macros"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["proc-macro"]

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = { version = "2.0.15", features = ["full"] }
